(#93) Extend workflow to publish a release artifact
salesforce/bazel-ls-vscode pull request #6
Opened 2021-05-04 07:32 UTC by PMitrafanau

2021-05-04 14:31 UTC, kkazakevich requested changes
can you add badge for build status to README.MD (like in ls-eclipse)?

2021-05-06 19:22 UTC, kkazakevich requested changes

2021-05-06 19:22 UTC, kkazakevich commented on README.md
> +![GitHub Actions](https://github.com/salesforce/bazel-eclipse-ls/workflows/build/badge.svg)
invalid URL, change to bazel-ls-vscode repo

2021-05-06 21:21 UTC, PMitrafanau commented on README.md
> +![GitHub Actions](https://github.com/salesforce/bazel-eclipse-ls/workflows/build/badge.svg)
Changed, thanks

2021-05-06 21:58 UTC, kkazakevich approved these changes

2021-05-07 12:13 UTC, merged